openapi: 3.0.3
info:
  title: Assignment API
  description: API for managing task assignments within projects
  version: 1.0.0
servers:
  - url: /api
    description: Assignment API server
tags:
  - name: Assignments
    description: Operations related to task assignments within projects
paths:
  /projects/{projectId}/assignments:
    get:
      tags:
        - Assignments
      summary: Get proposals for assigning tasks within a project
      operationId: getProposalForAssigningTasks
      parameters:
        - name: projectId
          in: path
          required: true
          description: The UUID of the project to get task assignment proposals for
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task assignment proposals retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AssignmentResponse'
        '404':
          description: Project not found
        '403':
          description: Forbidden
        '500':
          description: Internal server error
  /projects/{projectId}/assignments/{assignmentId}:
    post:
      tags:
        - Assignments
      summary: Set the decision for a specific task assignment
      operationId: setAssignment
      parameters:
        - name: projectId
          in: path
          required: true
          description: The UUID of the project the assignment belongs to
          schema:
            type: string
            format: uuid
        - name: assignmentId
          in: path
          required: true
          description: The UUID of the assignment to update
          schema:
            type: string
            format: uuid
      requestBody:
        description: The decision for the task assignment
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignmentDecision'
      responses:
        '200':
          description: Assignment decision set successfully
        '403':
          description: Forbidden
        '404':
          description: Project or assignment not found
        '500':
          description: Internal server error

components:
  schemas:
    AssignmentDecision:
      type: object
      properties:
        isAccepted:
          type: boolean
          description: Decision indicating whether the assignment is accepted or not
      required:
        - isAccepted

    AssignmentResponse:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
          description: The UUID of the task to be assigned
        developerId:
          type: string
          format: uuid
          description: The UUID of the developer to whom the task is assigned
        assignmentId:
          type: string
          format: uuid
          description: The UUID of the assignment

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]